name: Build and Deploy

on:
  push:
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      cancel-in-progress: false