name: Build Dist on Main

on:
  push:
    branches:
      - main
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    concurrency:
      group: build-main
      cancel-in-progress: true