name: Build and Deploy

on:
  push:
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml