name: Build Dist and Update Major Version Tag on Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    concurrency:
      group: build-{{ github.event.release.tag_name }}
      cancel-in-progress: true
    with:
      ref_name: ${{ github.event.release.tag_name }}
  notify_failure:
    needs: call-build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        run: |
          echo "::error::Build job has failed!"
          exit 1
  update-tag:
    needs: call-build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check and update major version tag
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION: ${VERSION}"
          MAJOR_VERSION="${VERSION%%.*}"
          echo "MAJOR_VERSION: ${MAJOR_VERSION}"
          
          echo "Current git tags:"
          git tag -l
          
          echo "Deleting existing major version tag..."
          git tag -d ${MAJOR_VERSION} || true
          git push --delete origin ${MAJOR_VERSION} || true
          
          echo "Creating new major version tag..."
          git tag -a ${MAJOR_VERSION} -m "Update ${MAJOR_VERSION} tag to ${VERSION}"
          git push origin ${MAJOR_VERSION}
          
          echo "Final git tags:"
          git tag -l