name: Update Major Version Tag

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check and update major version tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION="${VERSION%%.*}"
          
          # 기존 태그 삭제 (로컬과 원격 모두)
          git tag -d ${MAJOR_VERSION} || true
          git push --delete origin ${MAJOR_VERSION} || true
          
          # 새로운 태그 생성 및 푸시
          git tag -a ${MAJOR_VERSION} -m "Update ${MAJOR_VERSION} tag to ${VERSION}"
          git push origin ${MAJOR_VERSION}