name: Update Major Version Tag

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check and update major version tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION="v${VERSION%%.*}"
          
          if ! git show-ref --tags --verify --quiet "refs/tags/${MAJOR_VERSION}"; then
            git tag -a ${MAJOR_VERSION} -m "Update ${MAJOR_VERSION} tag to ${VERSION}"
            git push origin ${MAJOR_VERSION}
          else
            git tag -fa ${MAJOR_VERSION} -m "Update ${MAJOR_VERSION} tag to ${VERSION}"
            git push --force origin ${MAJOR_VERSION}
          fi